### ISSUE TITLE
Daftar bug januari

### ISSUE THREAD

**Issue by Beniferri** [mrsvette/simple-pos#11]
- [x] Jumlah tagihan yang tersimpan adalah jumlah yang dibayarkan
- [x] Harga diskon di produk tidak berkurang http://prntscr.com/dqjz0k
- [x] viewItems action tidak ada di controller, sehingga searching tidak jalan http://prntscr.com/dqk1cp
- [x] input diskon tidak langsung memotong total http://prntscr.com/dqkf80

**Comment by mrsvette** [comment]
@Beniferri : Pencarian barang melalui tombol pencarian lebih lanjut aman seharusnya http://awesomescreenshot.com/08467qey48, report jika di windows masih ga normal.
Harga diskon di produk ini sebenarnya adalah diskon untuk jumlah item/barang. Contoh jika harga nasi kebuli untuk setiap pembelian 2 item adalah seharga Rp. 150, yang harga aslinya seharusnya Rp.200 (@Rp.100) http://awesomescreenshot.com/07e67qfqd8, maka ditransaksi akan berlaku 
http://awesomescreenshot.com/0fa67qfn24 saat jumlah item diupdate

**Comment by mrsvette** [comment]
Should be fixed, please check the updated files https://github.com/mrsvette/simple-pos/commit/77175b8ef8ec0bb2c6fc16e427ca5ced717b52c2
